---
- name: Ping Pong Playbook
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: false
  
  tasks:
    - name: Ping remote host
      ping:
      
    - name: Pause for 2 seconds
      pause:
        seconds: 2
        
    - name: Ping the other host
      ping:
